const dati = [
  {
    site: {
      id: "351658_e6489b46ac73d5398916a5d7b30b800d",
      label: "ropelsw",
      status: "STOPPED",
      queuePos: 0,
      dbSize: 0,
      deleted: false,
      client: "kleecks",
      properties:
        '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
      instanceId: "ropelsw",
      domainId: 1,
      apikbase: "https://ovhservices.kleecks.com/SPServices/",
    },
    runInfo: {
      dups: 0,
      mat: 0,
      node: 0,
      queuePos: 0,
      rows: 215,
      scanned: 220,
      stats: 0,
      status: 0,
    },
    seeds: ["https://ropelsw.kleecks.com"],
    scans: [
      {
        scandate: "Mar 28, 2022 6:07:48 PM",
        id: 102186468,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: 0,
          fromCrawler: 37,
          fromSitemap: 0,
          fromSitemapOnly: 0,
          internal: 167,
          mimeALL: 153,
          mimeHTML: 80,
          mimeIMAGE: 23,
          noOkRobots: 0,
          okRobots: 0,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 28, 2022 5:55:50 PM",
        id: 102185750,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 171,
          mimeALL: 159,
          mimeHTML: 82,
          mimeIMAGE: 23,
          noOkRobots: null,
          okRobots: null,
          total: 171,
        },
        intinks: 1161,
        err0: 53,
        err1: 174,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4405,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 28, 2022 5:29:14 PM",
        id: 102184154,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 153,
          mimeHTML: 80,
          mimeIMAGE: 23,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 28, 2022 5:17:10 PM",
        id: 102183430,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 153,
          mimeHTML: 80,
          mimeIMAGE: 23,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4330,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 28, 2022 5:10:46 PM",
        id: 102183046,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 153,
          mimeHTML: 80,
          mimeIMAGE: 23,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 28, 2022 4:17:14 PM",
        id: 102179834,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 153,
          mimeHTML: 80,
          mimeIMAGE: 23,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 28, 2022 4:09:38 PM",
        id: 102179378,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 153,
          mimeHTML: 80,
          mimeIMAGE: 23,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1144,
        err0: 53,
        err1: 170,
        err2: 273,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4326,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 28, 2022 3:33:54 PM",
        id: 102177234,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 171,
          mimeALL: 159,
          mimeHTML: 82,
          mimeIMAGE: 23,
          noOkRobots: null,
          okRobots: null,
          total: 171,
        },
        intinks: 1161,
        err0: 53,
        err1: 174,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4406,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 28, 2022 2:22:06 PM",
        id: 102172926,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":false,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"[]\\\\\\"\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 110,
          mimeHTML: 43,
          mimeIMAGE: 20,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 21, 2022 9:42:43 AM",
        id: 101554963,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"[]\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 110,
          mimeHTML: 43,
          mimeIMAGE: 20,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 18, 2022 5:20:09 PM",
        id: 101323209,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"[]\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 110,
          mimeHTML: 43,
          mimeIMAGE: 20,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 18, 2022 5:08:22 PM",
        id: 101322502,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"[]\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 110,
          mimeHTML: 43,
          mimeIMAGE: 20,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 18, 2022 4:39:29 PM",
        id: 101320769,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"[]\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 110,
          mimeHTML: 43,
          mimeIMAGE: 20,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 18, 2022 3:51:29 PM",
        id: 101317889,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"[]\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: null,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 110,
          mimeHTML: 43,
          mimeIMAGE: 20,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1145,
        err0: 53,
        err1: 170,
        err2: 274,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4331,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Jan 18, 2022 2:45:31 PM",
        id: 96216331,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":false,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"\\"[]\\"","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 37,
          fromSitemap: 37,
          fromSitemapOnly: null,
          internal: 167,
          mimeALL: 110,
          mimeHTML: 43,
          mimeIMAGE: 20,
          noOkRobots: null,
          okRobots: null,
          total: 167,
        },
        intinks: 1185,
        err0: 53,
        err1: 171,
        err2: 276,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 4290,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Sep 20, 2021 4:47:24 PM",
        id: 85852044,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":true,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"[]","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 34,
          fromSitemap: 34,
          fromSitemapOnly: null,
          internal: 97,
          mimeALL: 140,
          mimeHTML: 78,
          mimeIMAGE: 21,
          noOkRobots: null,
          okRobots: null,
          total: 97,
        },
        intinks: 828,
        err0: 57,
        err1: 110,
        err2: 131,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 2976,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 23, 2021 4:46:16 PM",
        id: 70217176,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":true,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"[]","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 43,
          fromSitemap: 43,
          fromSitemapOnly: null,
          internal: 111,
          mimeALL: 154,
          mimeHTML: 78,
          mimeIMAGE: 30,
          noOkRobots: null,
          okRobots: null,
          total: 111,
        },
        intinks: 926,
        err0: 4,
        err1: 118,
        err2: 143,
        err3: 19,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 3298,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Mar 23, 2021 2:52:16 PM",
        id: 70210336,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":true,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"[]","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 43,
          fromSitemap: 43,
          fromSitemapOnly: null,
          internal: 111,
          mimeALL: 154,
          mimeHTML: 78,
          mimeIMAGE: 30,
          noOkRobots: null,
          okRobots: null,
          total: 111,
        },
        intinks: 927,
        err0: 23,
        err1: 118,
        err2: 144,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 3303,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
      {
        scandate: "Feb 16, 2021 12:16:41 PM",
        id: 67177001,
        bot: null,
        prefs:
          '{"responseRetries":"0","maxurl":"2000","ignoreNofollow":false,"collapsible":false,"maxlinksperurl":"100","maxcrawlerdepth":"3","followExt":true,"maxquerystrings":"3","noRescan":true,"id":"351658_e6489b46ac73d5398916a5d7b30b800d","maxThreads":"32","responseTimeout":"3000","crawlSitemap":true,"maxUrlThreads":"50","okRescan":"","seeds":["https://ropelsw.kleecks.com"],"addSitemaps":"","crawlCanon":true,"charsMin":"30","excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":"100","sizeMaxImages":"100","crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":"70","crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":"70","maxurllength":"999","crawlAllSubs":true,"maxdepth":"15","maxredirtofollow":"9","pixelsMax":"568","pixelsMinDescription":"400","renderText":true,"checkRDFa":true,"snippets":"[]","followInt":true,"charsMax":"65","checkDuplicates":false,"seed0":"https://ropelsw.kleecks.com","pixelsMin":"200","renderJS":false,"checkExt":true,"maxpagesize":"2000000","crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"ropelsw","checkJsonLD":true,"checkJS":true,"animationDuration":"300","charsMaxUrl":"115","checkImages":true,"pixelsMaxDescription":"970","charsMinDescription":"70","selectedItems":[],"urlsperdepth":"999","charsMaxDescription":"155"}',
        totalStats: {
          external: null,
          fromCrawler: 46,
          fromSitemap: 46,
          fromSitemapOnly: null,
          internal: 117,
          mimeALL: 162,
          mimeHTML: 82,
          mimeIMAGE: 32,
          noOkRobots: null,
          okRobots: null,
          total: 117,
        },
        intinks: 979,
        err0: 24,
        err1: 123,
        err2: 151,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 3507,
        instanceId: "351658_e6489b46ac73d5398916a5d7b30b800d",
      },
    ],
    lastUrls: [],
  },
  {
    site: {
      id: "88d016_1502ef90b94c12610dacac9ec43c9e45",
      label: "CFS",
      status: "STOPPED",
      queuePos: 0,
      dbSize: 0,
      deleted: false,
      client: "CFS",
      properties:
        '{"responseRetries":0,"maxurl":2000,"ignoreNofollow":false,"collapsible":false,"maxlinksperurl":100,"maxcrawlerdepth":3,"followExt":true,"maxquerystrings":3,"noRescan":true,"id":"88d016_1502ef90b94c12610dacac9ec43c9e45","maxThreads":32,"responseTimeout":3000,"crawlSitemap":true,"maxUrlThreads":50,"okRescan":"","seeds":["https://www.cfs.it/"],"addSitemaps":"","crawlCanon":true,"charsMin":30,"excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":100,"sizeMaxImages":100,"crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":70,"crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":70,"maxurllength":999,"crawlAllSubs":true,"maxdepth":15,"maxredirtofollow":9,"pixelsMax":568,"pixelsMinDescription":400,"renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":65,"checkDuplicates":false,"seed0":"https://www.cfs.it/","pixelsMin":200,"renderJS":false,"checkExt":true,"maxpagesize":2000000,"crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"CFS","checkJsonLD":true,"checkJS":true,"animationDuration":300,"charsMaxUrl":115,"checkImages":true,"pixelsMaxDescription":970,"charsMinDescription":70,"selectedItems":[],"urlsperdepth":999,"charsMaxDescription":155}',
      instanceId: "cfs",
      domainId: 1,
      apikbase: "https://ogservices.kleecks.com/SPServices/",
    },
    runInfo: {
      dups: 0,
      mat: 0,
      node: 0,
      queuePos: 0,
      rows: 1803,
      scanned: 1805,
      stats: 0,
      status: 0,
    },
    seeds: ["https://www.cfs.it/"],
    scans: [
      {
        scandate: "Mar 24, 2022 10:49:32 AM",
        id: 101818172,
        bot: null,
        prefs:
          '{"responseRetries":0,"maxurl":2000,"ignoreNofollow":false,"collapsible":false,"maxlinksperurl":100,"maxcrawlerdepth":3,"followExt":true,"maxquerystrings":3,"noRescan":true,"id":"88d016_1502ef90b94c12610dacac9ec43c9e45","maxThreads":32,"responseTimeout":3000,"crawlSitemap":true,"maxUrlThreads":50,"okRescan":"","seeds":["https://www.cfs.it/"],"addSitemaps":"","crawlCanon":true,"charsMin":30,"excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":100,"sizeMaxImages":100,"crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":70,"crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":70,"maxurllength":999,"crawlAllSubs":true,"maxdepth":15,"maxredirtofollow":9,"pixelsMax":568,"pixelsMinDescription":400,"renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":65,"checkDuplicates":false,"seed0":"https://www.cfs.it/","pixelsMin":200,"renderJS":false,"checkExt":true,"maxpagesize":2000000,"crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"CFS","checkJsonLD":true,"checkJS":true,"animationDuration":300,"charsMaxUrl":115,"checkImages":true,"pixelsMaxDescription":970,"charsMinDescription":70,"selectedItems":[],"urlsperdepth":999,"charsMaxDescription":155}',
        totalStats: {
          external: 0,
          fromCrawler: 1783,
          fromSitemap: 1270,
          fromSitemapOnly: 0,
          internal: 1803,
          mimeALL: 1792,
          mimeHTML: 1790,
          mimeIMAGE: 0,
          noOkRobots: 0,
          okRobots: 0,
          total: 1803,
        },
        intinks: 34211,
        err0: 286,
        err1: 10124,
        err2: 4276,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 166645,
        instanceId: "88d016_1502ef90b94c12610dacac9ec43c9e45",
      },
      {
        scandate: "Mar 14, 2022 11:01:43 PM",
        id: 100998103,
        bot: null,
        prefs:
          '{"responseRetries":0,"maxurl":2000,"ignoreNofollow":false,"collapsible":false,"maxlinksperurl":100,"maxcrawlerdepth":3,"followExt":true,"maxquerystrings":3,"noRescan":true,"id":"88d016_1502ef90b94c12610dacac9ec43c9e45","maxThreads":32,"responseTimeout":3000,"crawlSitemap":true,"maxUrlThreads":50,"okRescan":"","seeds":["https://www.cfs.it/"],"addSitemaps":"","crawlCanon":true,"charsMin":30,"excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":100,"sizeMaxImages":100,"crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":70,"crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":70,"maxurllength":999,"crawlAllSubs":true,"maxdepth":15,"maxredirtofollow":9,"pixelsMax":568,"pixelsMinDescription":400,"renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"[]\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\"\\\\\\"\\"","followInt":true,"charsMax":65,"checkDuplicates":false,"seed0":"https://www.cfs.it/","pixelsMin":200,"renderJS":false,"checkExt":true,"maxpagesize":2000000,"crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"CFS","checkJsonLD":true,"checkJS":true,"animationDuration":300,"charsMaxUrl":115,"checkImages":true,"pixelsMaxDescription":970,"charsMinDescription":70,"selectedItems":[],"urlsperdepth":999,"charsMaxDescription":155}',
        totalStats: {
          external: null,
          fromCrawler: 1783,
          fromSitemap: 1266,
          fromSitemapOnly: null,
          internal: 1814,
          mimeALL: 1793,
          mimeHTML: 1791,
          mimeIMAGE: null,
          noOkRobots: null,
          okRobots: null,
          total: 1814,
        },
        intinks: 34243,
        err0: 290,
        err1: 10129,
        err2: 4288,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 166736,
        instanceId: "88d016_1502ef90b94c12610dacac9ec43c9e45",
      },
      {
        scandate: "Mar 2, 2022 4:49:30 PM",
        id: 99938970,
        bot: null,
        prefs:
          '{"responseRetries":0,"maxurl":2000,"ignoreNofollow":false,"collapsible":false,"maxlinksperurl":100,"maxcrawlerdepth":3,"followExt":true,"maxquerystrings":3,"noRescan":true,"id":"88d016_1502ef90b94c12610dacac9ec43c9e45","maxThreads":32,"responseTimeout":3000,"crawlSitemap":true,"maxUrlThreads":50,"okRescan":"","seeds":["https://www.cfs.it/"],"addSitemaps":"","crawlCanon":true,"charsMin":30,"excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":100,"sizeMaxImages":100,"crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":70,"crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":70,"maxurllength":999,"crawlAllSubs":true,"maxdepth":15,"maxredirtofollow":9,"pixelsMax":568,"pixelsMinDescription":400,"renderText":true,"checkRDFa":true,"snippets":"\\"\\\\\\"[]\\\\\\"\\"","followInt":true,"charsMax":65,"checkDuplicates":false,"seed0":"https://www.cfs.it/","pixelsMin":200,"renderJS":false,"checkExt":true,"maxpagesize":2000000,"crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"CFS","checkJsonLD":true,"checkJS":true,"animationDuration":300,"charsMaxUrl":115,"checkImages":true,"pixelsMaxDescription":970,"charsMinDescription":70,"selectedItems":[],"urlsperdepth":999,"charsMaxDescription":155}',
        totalStats: {
          external: null,
          fromCrawler: 1802,
          fromSitemap: 1283,
          fromSitemapOnly: null,
          internal: 1822,
          mimeALL: 1813,
          mimeHTML: 1811,
          mimeIMAGE: null,
          noOkRobots: null,
          okRobots: null,
          total: 1822,
        },
        intinks: 34706,
        err0: 289,
        err1: 10237,
        err2: 4453,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 168176,
        instanceId: "88d016_1502ef90b94c12610dacac9ec43c9e45",
      },
      {
        scandate: "Feb 14, 2022 12:38:23 PM",
        id: 98541503,
        bot: null,
        prefs:
          '{"responseRetries":0,"maxurl":2000,"ignoreNofollow":false,"collapsible":false,"maxlinksperurl":100,"maxcrawlerdepth":3,"followExt":true,"maxquerystrings":3,"noRescan":true,"id":"88d016_1502ef90b94c12610dacac9ec43c9e45","maxThreads":32,"responseTimeout":3000,"crawlSitemap":true,"maxUrlThreads":50,"okRescan":"","seeds":["https://www.cfs.it/"],"addSitemaps":"","crawlCanon":true,"charsMin":30,"excludeUrl":"","includeUrl":"","checkOutDom":true,"charsMaxAlt":100,"sizeMaxImages":100,"crawlNextPrev":true,"checkMicrodata":true,"checkSWF":true,"checkCss":true,"pixelsMaxH1":70,"crawlAmp":true,"botAgent":"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)","respectRobots":false,"charsMaxH2":70,"maxurllength":999,"crawlAllSubs":true,"maxdepth":15,"maxredirtofollow":9,"pixelsMax":568,"pixelsMinDescription":400,"renderText":true,"checkRDFa":true,"snippets":"\\"[]\\"","followInt":true,"charsMax":65,"checkDuplicates":false,"seed0":"https://www.cfs.it/","pixelsMin":200,"renderJS":false,"checkExt":true,"maxpagesize":2000000,"crawlHrefLang":true,"multiple":false,"checkHrefLang":true,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","label":"CFS","checkJsonLD":true,"checkJS":true,"animationDuration":300,"charsMaxUrl":115,"checkImages":true,"pixelsMaxDescription":970,"charsMinDescription":70,"selectedItems":[],"urlsperdepth":999,"charsMaxDescription":155}',
        totalStats: {
          external: null,
          fromCrawler: 1971,
          fromSitemap: 1347,
          fromSitemapOnly: null,
          internal: 1999,
          mimeALL: 1994,
          mimeHTML: 1980,
          mimeIMAGE: null,
          noOkRobots: null,
          okRobots: null,
          total: 1999,
        },
        intinks: 36255,
        err0: 338,
        err1: 9531,
        err2: 4779,
        err3: 0,
        err4: 0,
        err0s: null,
        err1s: null,
        err2s: null,
        err3s: null,
        err4s: null,
        err0f: null,
        err1f: null,
        err2f: null,
        err3f: null,
        err4f: null,
        passed: 205639,
        instanceId: "88d016_1502ef90b94c12610dacac9ec43c9e45",
      },
    ],
    lastUrls: [],
  },
];

export default {
  getDati() {
    return dati;
  },
};
